export const DocsMap = {
  MAIN: ['Base', 'Introduction', 'Layout', 'Styles', 'Tasty API', 'Typography'],
  FORMS: [
    'Form',
    'Checkbox',
    'CheckboxGroup',
    'FileInput',
    'ComplexForm',
    'NumberInput',
    'PasswordInput',
    'RadioGroup',
    'SearchInput',
    'Switch',
    'TextArea',
    'TextInput',
  ],
  CONTENT: [
    'Result',
    'ActiveZone',
    'Alert',
    'Avatar',
    'Badge',
    'Card',
    'CopySnippet',
    'Placeholder',
    'PrismCode',
    'Skeleton',
    'Tag',
  ],
  ACTIONS: ['Button'],
  NAVIGATION: ['Tabs', 'Link'],
  OTHER: ['Base64Upload'],
  OVERLAYS: ['AlertDialog', 'DialogForm', 'Dialog', 'Notification', 'Tooltip'],
  PICKERS: ['ComboBox', 'Menu', 'Select'],
  HELPERS: ['Portal'],
  STATUS: ['LoadingAnimation', 'Spin'],
  GENERIC: ['Block', 'Paragraph', 'Text'],
}
