const DocsMap = {
  MAIN: [
    { name: 'Base', pathname: 'base' },
    { name: 'Introduction', pathname: '#' },
    { name: 'Layout', pathname: '#' },
    { name: 'Styles', pathname: '#' },
    { name: 'Tasty API', pathname: '#' },
    { name: 'Typography', pathname: '#' },
  ],
  FORMS: [
    { name: 'Form', pathname: '#' },
    { name: 'Checkbox', pathname: '#' },
    { name: 'CheckboxGroup', pathname: '#' },
    { name: 'FileInput', pathname: '#' },
    { name: 'ComplexForm', pathname: '#' },
    { name: 'NumberInput', pathname: '#' },
    { name: 'PasswordInput', pathname: '#' },
    { name: 'RadioGroup', pathname: '#' },
    { name: 'SearchInput', pathname: '#' },
    { name: 'Switch', pathname: '#' },
    { name: 'TextArea', pathname: '#' },
    { name: 'TextInput', pathname: '#' },
  ],
  CONTENT: [
    { name: 'Result', pathname: '#' },
    { name: 'ActiveZone', pathname: '#' },
    { name: 'Alert', pathname: '#' },
    { name: 'Avatar', pathname: '#' },
    { name: 'Badge', pathname: '#' },
    { name: 'Card', pathname: '#' },
    { name: 'CopySnippet', pathname: '#' },
    { name: 'Placeholder', pathname: '#' },
    { name: 'PrismCode', pathname: '#' },
    { name: 'Skeleton', pathname: '#' },
    { name: 'Tag', pathname: '#' },
  ],
  ACTIONS: [{ name: 'Button', pathname: '#' }],
  NAVIGATION: [
    { name: 'Tabs', pathname: '#' },
    { name: 'Link', pathname: '#' },
  ],
  OTHER: [{ name: 'Base64Upload', pathname: '#' }],
  OVERLAYS: [
    { name: 'AlertDialog', pathname: '#' },
    { name: 'DialogForm', pathname: '#' },
    { name: 'Dialog', pathname: '#' },
    { name: 'Notification', pathname: '#' },
    { name: 'Tooltip', pathname: '#' },
  ],
  PICKERS: [
    { name: 'ComboBox', pathname: '#' },
    { name: 'Menu', pathname: '#' },
    { name: 'Select', pathname: '#' },
  ],
  HELPERS: [{ name: 'Portal', pathname: '#' }],
  STATUS: [
    { name: 'LoadingAnimation', pathname: '#' },
    { name: 'Spin', pathname: '#' },
  ],
  GENERIC: [
    { name: 'Block', pathname: '#' },
    { name: 'Paragraph', pathname: '#' },
    { name: 'Text', pathname: '#' },
  ],
}

export default DocsMap
